spring:
  application:
    name: order-processing-service
  cloud:
    config:
      uri: http://config-server:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    jwt:
      secret: my-secret-key
      expiration: 86400000 # 1 day
